### ISSUE TITLE
[Bug] Failed to create the symbolic link. 

### ISSUE THREAD

**Issue by sentix001** [xenia-manager/xenia-manager#206]
2024-12-26 00:36:34.674 +01:00 [WRN] Configuration file 'F:\Game Setups (Multi-Platform)\_ROMS\_Emulators\XBOX360\XeniaX360\canary\Emulators\Xenia Canary\xenia-canary.config.toml' is missing. Creating a new one from default.
2024-12-26 00:36:34.680 +01:00 [ERR] Error during configuration reset
System.IO.IOException: Error changing configuration file for Canary: Failed to create the symbolic link.
 ---> System.InvalidOperationException: Failed to create the symbolic link.
   at XeniaManager.GameManager.ChangeConfigurationFile(String configurationFile, Nullable`1 xeniaVersion)
   --- End of inner exception stack trace ---
   at XeniaManager.GameManager.ChangeConfigurationFile(String configurationFile, Nullable`1 xeniaVersion)
   at XeniaManager.Installation.InstallationManager.ResetConfigFile(EmulatorVersion emulatorVersion)

2.0 crashing when pressing xenia config

**Comment by shazzaam7** [comment]
Can you check if the original configuration file is present? Should be in `F:\Game Setups (Multi-Platform)_ROMS_Emulators\XBOX360\XeniaX360\canary\Emulators\Xenia Canary\config\xenia-canary.config.toml`?

**Comment by sentix001** [comment]
it is    yes

**Comment by shazzaam7** [comment]
Are you running the Xenia Manager as Administrator?

**Comment by sentix001** [comment]
yes

**Comment by shazzaam7** [comment]
Can you try fresh reinstall?

**Comment by shazzaam7** [comment]
Hey, mind giving this [release](https://github.com/xenia-manager/xenia-manager/releases/tag/a80007d) with a potential fix a shot

**Comment by ixon8** [comment]
same here but slightly different, my file is there and when it crashes it deletes the file
2024-12-27 20:42:13.262 +01:00 [INF] Only Xenia Canary is installed
2024-12-27 20:42:13.264 +01:00 [INF] Checking for existing configuration file
2024-12-27 20:42:13.267 +01:00 [WRN] Configuration file 'C:\Users\kitkat\Desktop\xbox\Emulators\Xenia Canary\config\xenia-canary.config.toml' is missing. Creating a new one from default.
2024-12-27 20:42:13.267 +01:00 [ERR] Error during configuration reset
System.IO.IOException: Error changing configuration file for Canary: Could not find file 'C:\Users\kitkat\Desktop\xbox\Emulators\Xenia Canary\config\xenia-canary.config.toml'.
 ---> System.IO.FileNotFoundException: Could not find file 'C:\Users\kitkat\Desktop\xbox\Emulators\Xenia Canary\config\xenia-canary.config.toml'.
File name: 'C:\Users\kitkat\Desktop\xbox\Emulators\Xenia Canary\config\xenia-canary.config.toml'
   at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at XeniaManager.GameManager.ChangeConfigurationFile(String configurationFile, Nullable`1 xeniaVersion)
   --- End of inner exception stack trace ---
   at XeniaManager.GameManager.ChangeConfigurationFile(String configurationFile, Nullable`1 xeniaVersion)
   at XeniaManager.Installation.InstallationManager.ResetConfigFile(EmulatorVersion emulatorVersion)

**Comment by shazzaam7** [comment]
> same here but slightly different, my file is there and when it crashes it deletes the file 2024-12-27 20:42:13.262 +01:00 [INF] Only Xenia Canary is installed 2024-12-27 20:42:13.264 +01:00 [INF] Checking for existing configuration file 2024-12-27 20:42:13.267 +01:00 [WRN] Configuration file 'C:\Users\kitkat\Desktop\xbox\Emulators\Xenia Canary\config\xenia-canary.config.toml' is missing. Creating a new one from default. 2024-12-27 20:42:13.267 +01:00 [ERR] Error during configuration reset System.IO.IOException: Error changing configuration file for Canary: Could not find file 'C:\Users\kitkat\Desktop\xbox\Emulators\Xenia Canary\config\xenia-canary.config.toml'. ---> System.IO.FileNotFoundException: Could not find file 'C:\Users\kitkat\Desktop\xbox\Emulators\Xenia Canary\config\xenia-canary.config.toml'. File name: 'C:\Users\kitkat\Desktop\xbox\Emulators\Xenia Canary\config\xenia-canary.config.toml' at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite) at XeniaManager.GameManager.ChangeConfigurationFile(String configurationFile, Nullable`1 xeniaVersion) --- End of inner exception stack trace --- at XeniaManager.GameManager.ChangeConfigurationFile(String configurationFile, Nullable`1 xeniaVersion) at XeniaManager.Installation.InstallationManager.ResetConfigFile(EmulatorVersion emulatorVersion)

Can you try fresh install with the build I linked above?

**Comment by ixon8** [comment]
that is with that specific version, freshly installed

**Comment by shazzaam7** [comment]
> that is with that specific version, freshly installed

Can you provide me your log files (They're in the Logs folder). Upload them on [pastebin](https://pastebin.com/) or a similar site.

**Comment by shazzaam7** [comment]
Since no updates have been done here, I'm assuming this issue has been fixed. If there are any issues let me know, but for now I'll close this issue.
