### ISSUE TITLE
Looking for D drive??

### ISSUE THREAD

**Issue by Zer0Squared** [xenia-manager/xenia-manager#61]
**Describe the bug**
2024-07-30 09:00:33.837 -04:00 [INF] Loading new Settings Page and caching it for future use
2024-07-30 09:00:33.879 -04:00 [ERR] Object reference not set to an instance of an object.
Full Error:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Xenia_Manager.Pages.Settings.SelectTheme() in D:\This PC\Documents\Github\xenia-manager\Xenia Manager\Pages\Settings.xaml.cs:line 37
2024-07-30 09:00:37.723 -04:00 [ERR] Object reference not set to an instance of an object.
Full Error:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Xenia_Manager.Pages.Settings.LoadInstalledXeniaVersions() in D:\This PC\Documents\Github\xenia-manager\Xenia Manager\Pages\Settings.xaml.cs:line 72

**To Reproduce**
1. Start Program

**Expected behavior**
Expected program to run with no errors

**Screenshots**
N/A

**Additional context**
N/A

**Log File**
[Log-20240730.txt](https://github.com/user-attachments/files/16428423/Log-20240730.txt)

**Comment by shazzaam7** [comment]
I need more information. What did you exactly do? From the log files it looks like you just downloaded the program and opened it.

**Comment by shazzaam7** [comment]
Closing this issue due to lack of response.
